<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Skyline.DataMiner.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Skyline.DataMiner.CICD.Models.Protocol" Version="1.1.0" />
    <PackageReference Include="Skyline.DataMiner.Core.DataMinerSystem.Common" Version="1.1.3.8" />
    <PackageReference Include="Skyline.DataMiner.Dev.Common" Version="10.6.4" />
  </ItemGroup>

</Project>
