<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Skyline.DataMiner.CICD.Models.Protocol" Version="1.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Model\Creation\" />
    <Folder Include="Model\Table\" />
    <Folder Include="Model\Standalone\" />
  </ItemGroup>

</Project>
